docs(QTM-31): Updates versioning guide on contributting.md and…
catho/quantum pull request #323
Opened 2021-06-14 20:24 UTC by toncabral88

… contributors on readme.md

## Description
https://jirasoftware.catho.com.br/browse/QTM-31

## Review guide
- [ ] README.md
- [ ] Contributting.md

2021-06-16 15:31 UTC, matheusrpp submitted a review, later dismissed
## Review guide
- [x] README.md
- [x] Contributting.md

2021-06-22 14:58 UTC, rapahaeru requested changes
i think the `maintainers.md` file should be updated too.
add our names (and e-mail) in there.

2021-06-22 14:58 UTC, rapahaeru commented on CONTRIBUTING.MD
> +- Node installed at v12.16.1 and Yarn.
here, we should put 
"Node installed at v12.16.1 and Yarn. (to make it easier, we have .nvmrc, so just use `nvm use` to sets the repo default version of node)"

What do you think?

2021-06-22 14:58 UTC, rapahaeru commented on CONTRIBUTING.MD
> +    yarn commitizen
"yarn commitizen" (remember, before of to use commitizen, the packages should be installed previously)

WDYT?

2021-06-22 14:58 UTC, rapahaeru commented on CONTRIBUTING.MD
> +- [Eslint Airbnb](http://gitlab.devel/frontend-platform/quantum/blob/master/.eslintrc.js)
i didnt understand this references

2021-06-22 18:52 UTC, rapahaeru commented on CONTRIBUTING.MD
>  ## Submitting a Merge Request
Submitting a **Pull** Request

2021-06-22 18:53 UTC, rapahaeru commented on CONTRIBUTING.MD
>  1.  Fork the project, [Help Guide to Fork a repository](https://docs.gitlab.com/ce/gitlab-basics/fork-project.html/).
updates the url to github

2021-06-28 15:21 UTC, matheusrpp approved these changes
## Review guide
- [x] README.md
- [x] Contributting.md

2021-06-28 15:54 UTC, rapahaeru requested changes

2021-06-28 15:54 UTC, rapahaeru commented on CONTRIBUTING.MD
>  Open your pull request, if you don't know how do it, check this [tutorial](https://docs.gitlab.com/ee/gitlab-basics/add-merge-request.html/)
we are using a gitlab url here. use a github one.
(i did updated in catho-components a same url)

2021-06-28 15:54 UTC, rapahaeru commented on CONTRIBUTING.MD
> +- [Editorconfig](http://gitlab.devel/frontend-platform/quantum/blob/master/.editorconfig)
same here, this link does not exist.
I think is better to remove all this block

2021-06-28 15:54 UTC, rapahaeru commented on MAINTAINERS.md
> +- Matheus Rodrigues Pires ([matheus.pires@catho.com](mailto:matheus.pires@catho.com?Subject=Candidate%20Home%20Page%20Issue))
Clemente is missing.

2021-06-28 16:55 UTC, rapahaeru approved these changes

2021-06-28 17:40 UTC, matheusrpp approved these changes

2021-06-28 17:41 UTC, merged