feat(Qtm 282): Adding more icons
catho/quantum pull request #325
Opened 2021-06-16 19:42 UTC by matheusrpp

## Description
https://jirasoftware.catho.com.br/browse/QTM-282

## Setup
to view the components behavior, run `yarn storybook`

## Review guide
- [ ] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [ ] Unit tests (yarn test:components)
- [ ] Code review

### Browsers review
- [ ] Layout review
  - [ ] Edge
  - [ ] Firefox
  - [ ] Chrome
  - [ ] Safari
  - [ ] Mobile

2021-06-17 14:07 UTC, toncabral88 approved these changes
## Review guide
- [x] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [x] Unit tests (yarn test:components)
- [x] Code review

### Browsers review
- [x] Layout review
  - [x] Edge
  - [x] Firefox
  - [x] Chrome
  - [x] Safari
  - [x] Mobile

2021-06-22 14:13 UTC, rapahaeru requested changes
## Review guide
- [x] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [x] Unit tests (yarn test:components)
- [ ] Code review

### Browsers review
- [x] Layout review

2021-06-22 15:59 UTC, rapahaeru approved these changes

2021-06-22 17:32 UTC, toncabral88 approved these changes

2021-06-22 18:08 UTC, merged