chore(A11y checks): adds new a11y checks for pull requests template
catho/quantum pull request #346
Opened 2021-11-12 19:40 UTC by rapahaeru

## Setup
to view the components behavior, run `yarn storybook`

- [ ] Code review

2021-11-16 19:21 UTC, toncabral88 commented on docs/PULL_REQUEST_TEMPLATE.md
> +  - [ ] Identifiable through assistive technology (scree-reader chrome extension)?
```suggestion
  - [ ] Identifiable through assistive technology (screen-reader chrome extension)?
```

2021-11-16 19:23 UTC, toncabral88 requested changes
- [ ] Code review

2021-11-19 14:41 UTC, toncabral88 approved these changes

2021-11-19 14:41 UTC, matheusrpp approved these changes

2021-11-19 14:57 UTC, merged