feat(QTM-316): Adding typography mobile media query
catho/quantum pull request #353
Opened 2021-12-08 14:53 UTC by matheusrpp

## Description
https://jirasoftware.catho.com.br/browse/QTM-316

## Setup
to view the components behavior, run `yarn storybook`

## Review guide
- [ ] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [ ] Unit tests (yarn test:components)
- [ ] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [ ] Code review

### Browsers review
- [ ] Layout review
  - [ ] Edge
  - [ ] Firefox
  - [ ] Chrome
  - [ ] Safari
  - [ ] Mobile
- [ ] Ux review validation

2021-12-09 11:41 UTC, toncabral88 approved these changes
## Review guide
- [x] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [x] Unit tests (yarn test:components)
- [x] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [x] Code review

### Browsers review
- [x] Layout review

2021-12-13 18:01 UTC, rapahaeru requested changes
## Review guide
- [x] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [ ] Unit tests (yarn test:components)
- [x] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [ ] Code review

### Browsers review
- [ ] Layout review
- [ ] Ux review validation

2021-12-13 18:01 UTC, rapahaeru commented on components/GlobalStyle/sub-components/Typography.csr.unit.test.jsx
> +      `h2{font-size:32px;-webkit-letter-spacing:0.24px;-moz-letter-spacing:0.24px;-ms-letter-spacing:0.24px;letter-spacing:0.24px;}@media (min-width:1024px){h2{font-size:36px;-webkit-letter-spacing:0
if the font-size was wrong, updates here too.

2021-12-13 18:14 UTC, matheusrpp commented on components/GlobalStyle/sub-components/Typography.jsx
> +    font-size: 36px;
Mobile it's 32px and desktop it's 36px.
Desktop
![Captura de tela de 2021-12-13 15-13-09](https://user-images.githubusercontent.com/85566581/145865973-42c65df0-fa30-437e-a8de-635b94d76e3e.png)
Mobile
![Captura de tela de 2021-12-13 15-13-34](https://user-images.githubusercontent.com/85566581/145866070-27da154b-37a4-4fd2-a4b6-c9d949cf67df.png)

2021-12-13 18:34 UTC, rapahaeru approved these changes

2021-12-13 19:07 UTC, merged