chore(scripts): Sets component generator
catho/quantum pull request #357
Opened 2021-12-23 11:47 UTC by toncabral88

## Description
Sets a script to generate initial structure for a new component

## Setup
to view the components behavior, run `yarn storybook`

## Review guide
- [ ] Code review
- [ ] Generate new component
      - `yarn generate COMPONENT_NAME`

2021-12-23 18:28 UTC, tcelestino commented
@toncabral88 eu lembro no que create-catho-app tinha essa possibilidade de criar componente, acho que seria mais interessante usar lá. Deixo aqui algumas dúvidas:
- o Quantum deveria ser responsável por essa geração de componente? 
- quais foram os pensamentos de vocês para criar um gerador de componente dentro do quantum?

Só para entender melhor esse recurso novo no projeto. 🌵

2021-12-23 18:47 UTC, toncabral88 commented
> @toncabral88 eu lembro no que create-catho-app tinha essa possibilidade de criar componente, acho que seria mais interessante usar lá. Deixo aqui algumas dúvidas:
> 
> * o Quantum deveria ser responsável por essa geração de componente?
> * quais foram os pensamentos de vocês para criar um gerador de componente dentro do quantum?
> 
> Só para entender melhor esse recurso novo no projeto. cactus

A ideia aqui é criar uma estrutura mínima necessária para um novo componente no quantum . O objetivo é facilitar para a contribuição e até mesmo dar uma base do que é necessário para os novos componentes. Pelo que entendi o create-catho-app é para uso externo, no caso para utilizar uma estrutura com base no quantum. Esse generator seria para uso interno, o contribuinte não precisa se preocupar em criar arquivo por aquivo para o novo componente, basta rodar o comando e o necessário para o início do desenvolvimento estará lá.

2021-12-23 19:10 UTC, tcelestino commented
> > @toncabral88 eu lembro no que create-catho-app tinha essa possibilidade de criar componente, acho que seria mais interessante usar lá. Deixo aqui algumas dúvidas:
> > 
> > * o Quantum deveria ser responsável por essa geração de componente?
> > * quais foram os pensamentos de vocês para criar um gerador de componente dentro do quantum?
> > 
> > Só para entender melhor esse recurso novo no projeto. cactus
> 
> A ideia aqui é criar uma estrutura mínima necessária para um novo componente no quantum . O objetivo é facilitar para a contribuição e até mesmo dar uma base do que é necessário para os novos componentes. Pelo que entendi o create-catho-app é para uso externo, no caso para utilizar uma estrutura com base no quantum. Esse generator seria para uso interno, o contribuinte não precisa se preocupar em criar arquivo por aquivo para o novo componente, basta rodar o comando e o necessário para o início do desenvolvimento estará lá.

Entendi. Valeu pela info, @toncabral88

2021-12-28 13:33 UTC, tcelestino commented
@toncabral88 acho válido criar uma seção no README.md sobre esse novo recurso. Principalmente explicando como criar o componente.

2021-12-28 13:34 UTC, tcelestino submitted a review, later dismissed
- [x] Code review
- [x] Generate new component

2022-01-03 17:47 UTC, matheusrpp requested changes
## Review guide
- [ ] Code review
- [x] Generate new component
      - `yarn generate COMPONENT_NAME`

2022-01-03 17:47 UTC, matheusrpp commented on scripts/templates/component.js
> +  it('should math the snapshots', () => {
Typo "match"

2022-01-03 17:47 UTC, matheusrpp commented on scripts/templates/component.js
> +describe(<${componentName} />, () => {
Here I think the <${componentName} /> should be a string, isn't?

2022-01-03 17:47 UTC, matheusrpp commented on scripts/templates/component.js
> +        .toJson(),
And here I think  `.toJson()` should be `.toJSON()`, what do you think?

2022-01-06 16:33 UTC, matheusrpp approved these changes

2022-01-07 15:13 UTC, tcelestino approved these changes
- [x] Code review
- [x] Generate new component
      - `yarn generate COMPONENT_NAME`

2022-01-10 11:06 UTC, merged