chore(dependencies): Remove react imports from ts files
catho/quantum pull request #389
Opened 2022-03-04 14:07 UTC by toncabral88

## Description
Removers all react imports from project and updates script to generate new component

## Setup
to view the components behavior, run `yarn storybook`

## Review guide
- [ ] Code review
- [ ] TypeScript updated

2022-03-04 18:24 UTC, matheusrpp approved these changes
## Review guide
- [x] Code review
- [x] TypeScript updated

2022-03-04 18:42 UTC, rapahaeru requested changes

2022-03-04 18:42 UTC, rapahaeru commented on scripts/templates/component.js
>  const ${componentName} = ({ someProp }) => (
in line 9, the text is wrong.
`<h1>Hello, do domething here!</h1>`

2022-03-04 18:42 UTC, rapahaeru commented on scripts/templates/component-story.js
>    AutoExample,
Shouldnt this story be updated in new template of docs from storybook?
In this example, the storybook-ui still in use.

2022-03-04 18:43 UTC, rapahaeru commented
## Review guide
- [ ] Code review
- [x] TypeScript updated

2022-03-07 13:04 UTC, rapahaeru approved these changes

2022-03-07 18:13 UTC, matheusrpp approved these changes

2022-03-07 18:29 UTC, merged