Feat(TextArea AutoResize) - Adding autoResize function to textArea
catho/quantum pull request #394
Opened 2022-04-12 17:41 UTC by matheusrpp

## Description
Put the description of the task here.

## Setup
to view the components behavior, run `yarn storybook`

## Review guide
- [ ] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [ ] Unit tests (yarn test:components)
- [ ] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [ ] Code review
- [ ] TypeScript updated

### Browsers review
- [ ] Layout review
  - [ ] Edge
  - [ ] Firefox
  - [ ] Chrome
  - [ ] Safari
  - [ ] Mobile
- [ ] Ux review validation

2022-04-12 19:13 UTC, rapahaeru requested changes
Congrats!
the new dynamic it was good.

## Review guide
- [x] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [x] Unit tests (yarn test:components)
- [x] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [ ] Code review
- [x] TypeScript updated

### Browsers review
- [x] Layout review
- [ ] Ux review validation

2022-04-12 19:13 UTC, rapahaeru commented on components/TextArea/TextArea.jsx
> +    const previousRows = ev.target.rows;
how about of using destructuting here, to make code cleaner?
here my suggestions:
- i updated the contant names
- renamed the event arg
- and i applied a desctructuring in ev.target.
```
  onChangeTextArea = event => {
    const { target } = event;
    const { onChange } = this.props;
    const { minRows, maxRows } = this.state;
    const textareaLineHeightInPx = this._fontSize * this._lineHeight;
    const previousNumberRows = target.rows;
    target.rows = minRows;

    const currentNumberRows = Math.floor(
      target.scrollHeight / textareaLineHeightInPx,
    );
    
    if (currentNumberRows === previousNumberRows) {
      target.rows = currentNumberRows;
    }

    if (currentNumberRows >= maxRows) {
      target.rows = maxRows;
      target.scrollTop = target.scrollHeight;
    }

    const inputValue = event.currentTarget.value;
    this.setState({
      currentValue: inputValue,
      hasDefaultValue: null,
      rows: currentNumberRows < maxRows ? currentNumberRows : maxRows,
    });

    onChange(event);
  };
```

2022-04-12 19:13 UTC, rapahaeru commented on components/TextArea/TextArea.jsx
> +  autoResizeConfig: {
how about of:
```
  isAutoResize: false,
  autoResizeConfig: {
    initialRows: 1,
    minRows: 1,
    maxRows: 5,
  },
```

2022-04-12 19:13 UTC, rapahaeru commented on stories/TextArea/TextArea.regression-test.story.jsx
> +};
how about of a second example using the props?
```
export const AutoResizeWithMax3 = Template.bind({});
AutoResizeWithMax3.args = {
  autoResize: true,
  autoResizeConfig: {
    rowsConfig: 1,
    minRowsConfig: 1,
    maxRowsConfig: 3,
  },
};
```

2022-04-13 16:53 UTC, rapahaeru requested changes

2022-04-13 16:53 UTC, rapahaeru commented on components/TextArea/index.d.ts
> +    autoResize?: boolean;
i think you missed the update properties here

2022-04-14 15:15 UTC, toncabral88 reviewed
Very nice man!

- [x] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [x] Unit tests (yarn test:components)
- [x] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [x] Code review
- [x] TypeScript updated

### Browsers review
- [x] Layout review
  - [x] Edge
  - [x] Firefox
  - [x] Chrome
  - [x] Safari
  - [x] Mobile

2022-04-14 15:15 UTC, toncabral88 commented on components/TextArea/TextArea.jsx
> +  }),
How about check if `autoResizeConfig` is different of undefined to check if component is auto resize?

2022-04-18 19:08 UTC, rapahaeru approved these changes

2022-04-19 12:55 UTC, merged