feat: QTM-380 Updated documentation template
catho/quantum pull request #444
Opened 2022-10-11 19:26 UTC by douglasjr97

## Description
https://jirasoftware.catho.com.br/browse/QTM-380

## Review guide
- [ ] Code review
- [ ] Documentation

2022-10-14 20:13 UTC, MarcosViniciusPC requested changes
I have described some situations below that can be improved. Also, I believe it is necessary to include new examples of the popover with the props "inverted" and "visible". You can check examples of updated documentation to understand how we seek to exemplify the possible states of each component

2022-10-14 20:13 UTC, MarcosViniciusPC commented on stories/Popover/Popover.stories.jsx
> +  skin: 'primary',
In the same way that "placement" happens here with the "skin". If there is already an example of using the prop skin, you don't need other examples for all possible "skin" values

2022-10-14 20:13 UTC, MarcosViniciusPC commented on stories/Popover/Popover.stories.jsx
> +      <Row style={{ paddingTop: '72px', paddingLeft: '414px' }}>
We can follow the stylization adopted in the tooltip documentation in this case of not centering the popover using paddingLeft

2022-10-17 11:52 UTC, douglasjr97 commented on stories/Popover/Popover.stories.jsx
> +  direction: 'top',
Direction existed in popover Popover.regression-test.story.jsx

2022-10-17 12:16 UTC, MarcosViniciusPC commented on stories/Popover/Popover.stories.jsx
> +  direction: 'top',
The "direction" argument is passed to the "placement" property in the popover component's regression tests template. I recommend not doing this. I find it much more interesting to check and pass the properties of each component as defined propTypes.

2022-10-18 12:26 UTC, MarcosViniciusPC requested changes
In addition to the points mentioned below, I also think it's necessary to include an example using the "visible" property

2022-10-18 12:26 UTC, MarcosViniciusPC commented on stories/Popover/Popover.stories.jsx
> +      }}
Just a padding of 72px I believe is enough

2022-10-18 12:26 UTC, MarcosViniciusPC commented on stories/Popover/Popover.stories.jsx
> +Default.args = {};
```suggestion
```
When an example has no parameters it is not necessary to include an "args" object

2022-10-18 12:26 UTC, MarcosViniciusPC commented on stories/Popover/Popover.stories.jsx
> +  placement: 'top',
I see no need to include this parameter in this scenario

2022-10-18 17:45 UTC, MarcosViniciusPC approved these changes
[x] Code review
[x] Documentation

2022-10-18 18:10 UTC, merged