fix(QTM-415):  Update ts file with new property to hide last page
catho/quantum pull request #446
Opened 2022-10-17 15:31 UTC by MarcosViniciusPC

## Description
https://jirasoftware.catho.com.br/browse/QTM-415

## Setup
to view the components behavior, run `yarn storybook`

## Review guide
- [ ] Unit tests (yarn test:components)
- [ ] Regression
- [ ] Code review
- [ ] TypeScript updated

2022-10-17 18:24 UTC, douglasjr97 requested changes
you should adjust the logic.
 
![image](https://user-images.githubusercontent.com/37362664/196253489-5761bccc-6ad3-4205-b054-75020b1ca795.png) 

![image](https://user-images.githubusercontent.com/37362664/196253808-5a161f52-d7d9-4fe5-b36a-d38a026cf031.png)

2022-10-17 18:24 UTC, douglasjr97 commented on components/Pagination/utils/pagination.js
>        visiblePages = [...visiblePages, lastPage];
```suggestion
    if (hideLastPagination) {
      visiblePages = [...visiblePages, lastPage];
```

you should adjust the logic with a hideLastPagination being true.

2022-10-18 14:56 UTC, douglasjr97 approved these changes
## Review guide
- [x] Unit tests (yarn test:components)
- [x] Regression
- [x] Code review
- [x] TypeScript updated

2022-10-18 17:08 UTC, MarcosViniciusPC commented
> shouldn't it start in hiding?

No, the default behavior is always visible.

2022-10-18 17:11 UTC, merged