build(QTM-420): Updated loader-utils to version 2.0.2
catho/quantum pull request #461
Opened 2022-11-25 18:50 UTC by MarcosViniciusPC

## Description
https://jirasoftware.catho.com.br/browse/QTM-420

## Review guide
- [ ] Unit tests
- [ ] Regression
- [ ] Code review
- [ ] Documentation
- [ ] Build

2022-11-28 19:15 UTC, rapahaeru requested changes
i think we should update this libs in another way.
updating the yarn.lock file, i think its not a good practice.

2022-11-29 14:38 UTC, douglasjr97 approved these changes
## Review guide
- [x] Unit tests
- [x] Regression
- [x] Code review
- [x] Documentation
- [x] Build

2022-11-29 19:24 UTC, douglasjr97 approved these changes

2022-11-29 20:56 UTC, rapahaeru approved these changes
## Review guide
- [x] Unit tests
- [x] Regression
- [x] Code review
- [x] Documentation
- [] Build

2022-11-30 11:58 UTC, merged