creating a new branch
catho/quantum pull request #485
Opened 2023-03-13 19:56 UTC by alizeleal

## Description
Put the description of the task here.

## Setup
to view the components behavior, run `yarn storybook`

## Review guide
- [ ] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [ ] Unit tests (yarn test:components)
- [ ] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [ ] Code review
- [ ] TypeScript updated

### A11y review
- [ ] A11y checks
  - [ ] accessible via keyboard?
  - [ ] Identifiable through assistive technology (screen-reader chrome extension)?
  - [ ] Semantically correct html elements (or if necessary identified by WAI-ARIA)?
  - [ ] Is there a deficiency in color contrast?

### Browsers review
- [ ] Layout review
  - [ ] Edge
  - [ ] Firefox
  - [ ] Chrome
  - [ ] Safari
  - [ ] Mobile
- [ ] Ux review validation

2023-03-20 18:07 UTC, rapahaeru commented on CONTRIBUTING.MD
> +- To collaborate with this project, for security reasons, a Token is needed. More info in [confluence of the project](https://confluence.catho.com.br/pages/viewpage.action?pageId=51675150);
Exactly! I copied text from Catho components and didn't see this line.

2023-03-20 19:40 UTC, rapahaeru requested changes
Alize, I think you are not using `commitizen` to push your updates.
Please re-commit using it, so semantic-release can version your updates.

2023-03-21 13:02 UTC, MarcosViniciusPC approved these changes
[x] Documentation

2023-03-21 15:35 UTC, douglasjr97 approved these changes
## Review guide
- [x] Documentation

2023-03-22 12:23 UTC, merged