docs(documentation): QTM-450 - Editing an existing component
catho/quantum pull request #487
Opened 2023-03-22 13:05 UTC by alizeleal

## Description
https://jirasoftware.catho.com.br/browse/QTM-450

## Setup
to view the components behavior, run `yarn storybook`

## Review guide
- [ ] Documentation

2023-03-23 19:56 UTC, MarcosViniciusPC approved these changes

2023-03-23 19:56 UTC, MarcosViniciusPC commented on CONTRIBUTING.MD
> +        Open your pull request. PIf you don't know how do it, check this [tutorial](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-request
```suggestion
        Open your pull request. If you don't know how do it, check this [tutorial](https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).
```

2023-03-23 19:58 UTC, MarcosViniciusPC requested changes
I believe there was a typo above, could you adjust it?

2023-03-24 11:47 UTC, MarcosViniciusPC approved these changes
[x] Documentation

2023-03-24 18:29 UTC, rapahaeru approved these changes

2023-03-24 18:49 UTC, merged