Perf(QTM-494): Replacement of the material by the mui
catho/quantum pull request #508
Opened 2023-06-26 15:28 UTC by MarcosViniciusPC

## Description
https://jirasoftware.catho.com.br/browse/QTM-494

## Review guide
- [ ] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [ ] Unit tests (yarn test:components)
- [ ] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [ ] Doc (yarn storybook)
- [ ] Build
- [ ] Code review

### Browsers review
- [ ] Layout review
  - [ ] Chrome
  - [ ] Safari
  - [ ] Mobile

2023-06-26 18:56 UTC, alizeleal submitted a review, later dismissed

2023-06-26 18:58 UTC, alizeleal reviewed
- [x] Coverage (coverage status should not regress)
- yarn test:coverage

- [x]  Unit tests (yarn test:components)
- [x] Regression
- first start the storybook for regression tests(and keep it open):  yarn test:regression:storybook;
- then run the regression tests: yarn test:regression
- [x]  Doc (yarn storybook)
- [x]  Build


 Layout review
- [x]  Chrome

2023-06-27 13:07 UTC, rapahaeru requested changes
[Comment removed]

2023-06-27 18:25 UTC, rapahaeru requested changes
## Review guide
- [x] Coverage (coverage status should not regress)\
      - `yarn test:coverage`
- [x] Unit tests (yarn test:components)
- [x] Regression \
      - first start the storybook for regression tests(and keep it open): ` yarn test:regression:storybook`; \
      - then run the regression tests: `yarn test:regression`
- [x] Doc (yarn storybook)
- [x] Build
- [ ] Code review

### Browsers review
- [x] Layout review
  - [x] Chrome
  - [x] Safari
  - [x] Mobile

2023-06-27 18:25 UTC, rapahaeru commented on components/RangeSlider/RangeSlider.jsx
> +      color: `${primary[700]} !important`,
do we need this important?

2023-06-27 18:25 UTC, rapahaeru commented on components/RangeSlider/RangeSlider.jsx
> +      backgroundColor: `${disabled ? neutral[500] : primary[700]} !important`,
do we need this important?

2023-06-27 18:25 UTC, rapahaeru commented on components/RangeSlider/RangeSlider.jsx
> +      backgroundColor: `${disabled ? neutral[500] : primary[700]} !important`,
do we need this important?

2023-06-27 18:25 UTC, rapahaeru commented on components/RangeSlider/RangeSlider.jsx
> +      height: `8px !important`,
do we need all this important?

2023-06-27 18:25 UTC, rapahaeru commented on components/RangeSlider/RangeSlider.jsx
> +      left: `${halfMeasure} !important`,
do we need this important?

2023-06-27 18:25 UTC, rapahaeru commented on components/RangeSlider/RangeSlider.jsx
> +      padding: '0px !important',
do we need this important?

2023-06-27 18:25 UTC, rapahaeru commented on components/RangeSlider/RangeSlider.jsx
> +      borderRadius: `4px !important`,
do we need this important?

2023-06-27 18:25 UTC, rapahaeru commented on components/RangeSlider/RangeSlider.jsx
> +      border: 'none !important',
do we need this important?

2023-06-27 18:25 UTC, rapahaeru commented on components/RangeSlider/RangeSlider.jsx
> +      backgroundColor: `${hexToRgba(primary[700], 0.5)} !important`,
do we need this important?

2023-06-27 18:25 UTC, rapahaeru commented on components/RangeSlider/RangeSlider.jsx
> +      height: `8px !important`,
do we need this important?

2023-06-27 18:25 UTC, rapahaeru commented on components/RangeSlider/RangeSlider.jsx
> +      borderRadius: `4px !important`,
do we need this important?

2023-06-27 18:25 UTC, rapahaeru commented on components/RangeSlider/RangeSlider.jsx
> +      color: `${disabled ? neutral[500] : primary[700]} !important`,
do we need this important?

2023-06-28 19:45 UTC, rapahaeru submitted a review, later dismissed

2023-06-29 19:02 UTC, rapahaeru approved these changes

2023-06-29 20:08 UTC, alizeleal approved these changes
- [x] Coverage (coverage status should not regress)

- yarn test:coverage
 

- [x] Unit tests (yarn test:components)

 

- [x] Regression

- first start the storybook for regression tests(and keep it open):  yarn test:regression:storybook;
- then run the regression tests: yarn test:regression

- [x]  Doc (yarn storybook)
- [x]  Build

2023-06-30 11:25 UTC, MarcosViniciusPC commented on components/RangeSlider/RangeSlider.jsx
> +      color: `${primary[700]} !important`,
It's not necessary, I removed it

2023-06-30 11:26 UTC, MarcosViniciusPC commented on components/RangeSlider/RangeSlider.jsx
> +      backgroundColor: `${disabled ? neutral[500] : primary[700]} !important`,
It's not necessary, I removed it

2023-06-30 11:26 UTC, MarcosViniciusPC commented on components/RangeSlider/RangeSlider.jsx
> +      backgroundColor: `${disabled ? neutral[500] : primary[700]} !important`,
It's not necessary, I removed it

2023-06-30 11:27 UTC, MarcosViniciusPC commented on components/RangeSlider/RangeSlider.jsx
> +      height: `8px !important`,
It's not necessary, I removed it

2023-06-30 11:27 UTC, MarcosViniciusPC commented on components/RangeSlider/RangeSlider.jsx
> +      left: `${halfMeasure} !important`,
It's not necessary, I removed it

2023-06-30 11:27 UTC, MarcosViniciusPC commented on components/RangeSlider/RangeSlider.jsx
> +      border: 'none !important',
It's not necessary, I removed it

2023-06-30 11:27 UTC, MarcosViniciusPC commented on components/RangeSlider/RangeSlider.jsx
> +      backgroundColor: `${hexToRgba(primary[700], 0.5)} !important`,
It's not necessary, I removed it

2023-06-30 11:27 UTC, MarcosViniciusPC commented on components/RangeSlider/RangeSlider.jsx
> +      height: `8px !important`,
It's not necessary, I removed it

2023-06-30 11:27 UTC, MarcosViniciusPC commented on components/RangeSlider/RangeSlider.jsx
> +      borderRadius: `4px !important`,
It's not necessary, I removed it

2023-06-30 11:28 UTC, MarcosViniciusPC commented on components/RangeSlider/RangeSlider.jsx
> +      color: `${disabled ? neutral[500] : primary[700]} !important`,
It's not necessary, I removed it

2023-06-30 13:42 UTC, rapahaeru submitted a review, later dismissed

2023-07-03 13:03 UTC, alizeleal approved these changes
- [x] Coverage (coverage status should not regress)

- yarn test:coverage
 

- [x] Unit tests (yarn test:components)

 

- [x] Regression

- first start the storybook for regression tests(and keep it open):  yarn test:regression:storybook;
- then run the regression tests: yarn test:regression

- [x]  Doc (yarn storybook)
- [x]  Build

2023-07-03 13:05 UTC, merged