docs(QTM-698): Inclusion in the docs of the suggestion not to use MUI in implem
catho/quantum pull request #559
Opened 2024-05-07 12:37 UTC by MarcosViniciusPC

## Description
https://jirasoftware.catho.com.br/browse/QTM-698

## Review guide
- [ ] Doc

2024-05-08 13:24 UTC, rapahaeru submitted a review, later dismissed

2024-05-09 12:49 UTC, alizeleal commented on CONTRIBUTING.MD
> +The MUI library, as well as the Styled Components, internally use resources and libraries that are an impediment to the use of [Server Components](https://nextjs.org/docs/app/building-your-applicatio
The MUI library, as well as the Styled Components, uses internally resources and libraries that aren't compatible with [Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components), a resource added to Next JS 13. We intend to enable its use in the future to improve the performance of our components. Therefore, we plan to remove the mentioned libraries completely from our components.

2024-05-09 12:55 UTC, alizeleal requested changes

2024-05-09 12:55 UTC, alizeleal commented on CONTRIBUTING.MD
> +The MUI library, as well as the Styled Components, internally use resources and libraries that are an impediment to the use of [Server Components](https://nextjs.org/docs/app/building-your-applicatio
The MUI library, as well as the Styled Components, uses internally resources and libraries that aren't compatible with [Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components), a resource added to Next JS 13. We intend to enable its use in the future to improve the performance of our components. Therefore, we plan to remove the mentioned libraries completely from our components.

2024-05-09 12:55 UTC, alizeleal commented on CONTRIBUTING.MD
> +We also do not recommend using any other ready-made component libraries. We suggest that new components have their DOM structure, styling and functionalities completely implemented internally, that i
Also, we do not recommend using any other ready-made component library. We suggest for new components to have DOM structure, styling and functionalities completely implemented internally, without any dependence on third-party libraries.

2024-05-09 12:55 UTC, alizeleal commented on README.md
> +For performance and long-term maintenance reasons, we do not recommend using [MUI](https://mui.com/material-ui/getting-started/) in Quantum component implementations. MUI is included in our library o
For performance and long-term maintenance reasons, we do not recommend using [MUI](https://mui.com/material-ui/getting-started/) in Quantum components implementation. MUI is present in our library only to allow the use of [Material Icons](https://mui.com/material-ui/material-icons/).

2024-05-09 12:55 UTC, alizeleal commented on README.md
> +We also do not recommend using any other ready-made component libraries. We suggest that new components have their DOM structure, styling and functionalities completely implemented internally, that i
Also, we do not recommend using any other ready-made component library. We suggest for new components to have DOM structure, styling and functionalities completely implemented internally, without any dependence on third-party libraries.

2024-05-09 12:58 UTC, alizeleal requested changes

2024-05-09 12:58 UTC, alizeleal commented on CONTRIBUTING.MD
> +The MUI library, as well as the Styled Components, internally use resources and libraries that are an impediment to the use of [Server Components](https://nextjs.org/docs/app/building-your-applicatio
```suggestion
The MUI library, as well as the Styled Components, uses internally resources and libraries that aren't compatible with [Server Components](https://nextjs.org/docs/app/building-your-application/rendering/server-components), a resource added to Next JS 13. We intend to enable its use in the future to improve the performance of our components. Therefore, we plan to remove the mentioned libraries completely from our components.
```

2024-05-09 12:58 UTC, alizeleal commented on CONTRIBUTING.MD
> +We also do not recommend using any other ready-made component libraries. We suggest that new components have their DOM structure, styling and functionalities completely implemented internally, that i
```suggestion
Also, we do not recommend using any other ready-made component library. We suggest for new components to have DOM structure, styling and functionalities completely implemented internally, without any dependence on third-party libraries.
```

2024-05-09 12:58 UTC, alizeleal commented on README.md
> +For performance and long-term maintenance reasons, we do not recommend using [MUI](https://mui.com/material-ui/getting-started/) in Quantum component implementations. MUI is included in our library o
```suggestion
For performance and long-term maintenance reasons, we do not recommend using [MUI](https://mui.com/material-ui/getting-started/) in Quantum components implementation. MUI is present in our library only to allow the use of [Material Icons](https://mui.com/material-ui/material-icons/).
```

2024-05-09 12:58 UTC, alizeleal commented on README.md
> +We also do not recommend using any other ready-made component libraries. We suggest that new components have their DOM structure, styling and functionalities completely implemented internally, that i
```suggestion
Also, we do not recommend using any other ready-made component library. We suggest for new components to have DOM structure, styling and functionalities completely implemented internally, without any dependence on third-party libraries.
```

2024-05-09 14:12 UTC, alizeleal approved these changes

2024-05-10 17:21 UTC, merged